cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    1ms21ci004:
      email: 1MS21CI004@msrit.edu
      name: ANIRUDDH MANTRALA
      password: $2b$12$gt8FNHUK2jChzB8pZ.ui6OedYHl5rimFikImq6naaaO8RyhlXzeUi
    1ms21ci006:
      email: 1MS21CI006@msrit.edu
      name: ANSH SINGHAL
      password: $2b$12$o2/csUuldcVCGl35RRIMN.fln0KuBPA23nAesH3l06bqnX7ayUd22
    1ms21ci049:
      email: 1MS21CI049@msrit.edu
      name: SHRAVAN
      password: $2b$12$8O31XBc7XKzpmep192Ph9uiAseCv670/FyDq82lYtexR.lreiDRYS
    1ms21ci055:
      email: 1MS21CI055@msrit.edu
      name: SIDDHARTH RAO KODIKAL
      password: $2b$12$q8m.Kd.Te/G5yPEeVcDPiOkMER/5mgzhrZAR1GMuyHyzgKXrFJ52C
    1ms21ci056:
      email: 1MS21CI056@msrit.edu
      name: SIRI R S
      password: $2b$12$Uhf62DO3YZNhZQnJNMTyCeDy74U79BUJIfRj1Jk3DKNFAAzgyJBBW
    1ms21ci057:
      email: 1MS21CI057@msrit.edu
      name: SUHA JAMEEL S
      password: $2b$12$ZCVjvcKkHPBNON3r3kHWZeFddcWF7B9yVkCgehFUMhMlZ6nsrmDRq
    1ms21is014:
      email: 1MS21IS014@msrit.edu
      name: AKHILESH
      password: $2b$12$/4Xv7GekjzyYBqArkZwFH.5wedMdd70nPXo68.Pk9epavIuJBDc4G
    1ms21is016:
      email: 1MS21IS016@msrit.edu
      name: AMITESH VERMA
      password: $2b$12$41EETWXe6ciOs/uvA9YSs.BasWp0pRTo6OtW8nTkc2yDCTxVR7AvK
    1ms21is017:
      email: 1MS21IS017@msrit.edu
      name: AMITH
      password: $2b$12$j49h0HC8BB9NnaqbwJFvaejUVAAz7.p0WvVYNnHCf7rXFiAt6Crq2
    1ms22ai017-t:
      email: 1MS22AI017-T@msrit.edu
      name: SANA ABDUL RAHIMAN
      password: $2b$12$gtUptqxzM0BmKKSmHrEROukEwdLTNRQcPJ/J53/KwXy6gwCtEUT2S
