1MS21CI004:
  email: 1MS21CI004@msrit.edu
  name: ANIRUDDH MANTRALA
  password: $2b$12$ZzLQjbX83BDhPv2Vc7zdrus0rrU8mSrzhXPPnh.HHcWPTUb2rSO22
1MS21CI006:
  email: 1MS21CI006@msrit.edu
  name: ANSH SINGHAL
  password: $2b$12$0EKEbu8KpgkTpPyUaKkq5uh6qahoDbThb4tL/2SK6y58rXtS50eJq
1MS21CI049:
  email: 1MS21CI049@msrit.edu
  name: SHRAVAN
  password: $2b$12$MsSdW8cma6XulM5hMSTxluCggUCRFN0/jHC.4ijNA/CwWHcGNODLy
1MS21CI055:
  email: 1MS21CI055@msrit.edu
  name: SIDDHARTH RAO KODIKAL
  password: $2b$12$FpY92LFCzLbZ0NajN9zce.3nfdEgQiCtpPcoZf8nT92sevCrM0.LK
1MS21CI056:
  email: 1MS21CI056@msrit.edu
  name: SIRI R S
  password: $2b$12$feTy/hxhQ3J6paIFgX2tuOwSfHjahFL/VX.FaRE/F5BnTrHC2Ug5u
1MS21CI057:
  email: 1MS21CI057@msrit.edu
  name: SUHA JAMEEL S
  password: $2b$12$eHvBSmGHZvecPSg3fa/co.HD2/fw.EA01LGQJC9fGfeWKwFIfkmU6
1MS21IS014:
  email: 1MS21IS014@msrit.edu
  name: AKHILESH
  password: $2b$12$8DcqtuoLjulSNYvkiu8kK.lTXfWxBPESzlKHIMl4ngYBJMYr/k0lK
1MS21IS016:
  email: 1MS21IS016@msrit.edu
  name: AMITESH VERMA
  password: $2b$12$q0qtOWyydvhfyWyjhE6jzea5HHrDBEAYxwdIIFze8i.Q0NtirvGq.
1MS21IS017:
  email: 1MS21IS017@msrit.edu
  name: AMITH
  password: $2b$12$rGjqVoglmOrJeJ75oNeAqOziEB6AYl00dvhgz1k0kloedzqLKHWea
1MS22AI017-T:
  email: 1MS22AI017-T@msrit.edu
  name: SANA ABDUL RAHIMAN
  password: $2b$12$rkDBhoVvmnHzOz82RK0MGek9hf32uBKYWw4lZk0Bbw.2B1Ke1aaC2
